language: php

php:
  - 7.0
#  - hhvm

services:
  - mysql

before_script:
  - cp app/config/config_test.yml.travis app/config/config_test.yml
  - cp ./phpunit.xml.dist ./phpunit.xml
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'create database IF NOT EXISTS trektoursapi;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php bin/console doctrine:database:create --env=test --if-not-exists
  - php bin/console cache:clear --env=test
  - php bin/console doctrine:schema:update --force --env=test

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)