api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    defaults: { _format: "json" }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc